### PR TITLE
HAL-1720 MYSQL Datasource create with incorrect default validation settings

### PR DESCRIPTION
**Pull request by Amitninja12345**
…ttings

### CODE REVIEW

**Review by Amitninja12345 — COMMENTED** [review]
@hpehl  please review it.

**Comment by hpehl** [comment]
Sorry for the delay @Amitninja12345 I'll try to review asap.

**Comment by Amitninja12345** [comment]
@hpehl ack

**Comment by hpehl** [comment]
Thanks for the contribution @Amitninja12345 
Superseded by #445.

**Pull request closed without merging**
