### PR TITLE
[HAL-1303] Add validator for duplicate names on tables

### PR DESCRIPTION
**Pull request by MMarus**
HAL issue: https://issues.jboss.org/browse/HAL-1303

### CODE REVIEW

**Comment by hpehl** [comment]
Thanks for your contribution @MMarus. I think it's a good proposal to validate for duplicate names on the client side instead of showing a somehow cryptic error message from the server side. 

Currently, the form item validation is meant to be synchronous. This makes checking for duplicated resources a little bit complicated. I can think of two ways to implement the validator:

1. Implement a simple synchronous validator:

```java
public class UniqueNameValidation implements FormItemValidation<String> {

    private final Set<String> names;

    public UniqueNameValidation(String... names) {
        this.names = new HashSet<>();
        this.names.addAll(asList(names));
    }

    @Override
    public ValidationResult validate(String value) {
        if (names.contains(value)) {
            return ValidationResult.invalid("Duplicate resource!");
        }
        return ValidationResult.OK;
    }
}
```

This would require that the existing resource names are known at creation time of `UniqueNameValidation`. Most often this is already the case. We often know the deployments which are a finder column or the items which are shown in a table. The only drawback is that it's not as accurate as if we check the resources on the server side. 

2. Support async form item validation: I can think of an interface like 

```java
public interface AsyncFormItemValidation<T> {

    void validate(T value, Consumer<ValidationResult> callback);
}
```

and an implementation like: 

```java
public class UniqueNameValidation implements AsyncFormItemValidation<String> {

    private final Dispatcher dispatcher;
    private final ResourceAddress parent;

    public UniqueNameValidation(Dispatcher dispatcher, ResourceAddress parent) {
        this.dispatcher = dispatcher;
        this.parent = parent;
    }

    @Override
    public void validate(String value, Consumer<ValidationResult> callback) {
        Operation operation = new Operation.Builder(parent, READ_CHILDREN_NAMES_OPERATION).build();
        dispatcher.execute(operation, result -> {
            Set<String> names = result.asList().stream().map(ModelNode::asString).collect(toSet());
            if (names.contains(value)) {
                callback.accept(ValidationResult.invalid("Duplicate resource!"));
            } else {
                callback.accept(ValidationResult.OK);
            }
        });
    }
}
```

This approach would require some changes in the form though. We would need to defer form operations like add and save until all async validation have finished. I'm not sure whether this can be easily integrated into the synchronous form operation workflow.

So I would opt for the first approach.

**Comment by MMarus** [comment]
Thank you very much for the explanation. I would go with the first option as well. Therefore, I am going to try to implement it synchronously with use of the resource list in the "finder column" or the items which are shown in the table.

**Comment by MMarus** [comment]
@hpehl I have used the list of resources from the finder column during the creation of the validator.

The usage could be as in the [JdbcDriverColumn.java](https://github.com/hal/console/pull/241/files#diff-54e507522bd2213693a7939eafdd25bbR119):
```java
String[] names = getCurrentItems().stream().map(JdbcDriver::getName).toArray(String[]::new);
form.getFormItem(DRIVER_NAME).addValidationHandler(new UniqueNameValidation<>(names));
```  

WDYT? 
If you like this approach I could start incorporating it into other columns which have the add option.

**Comment by hpehl** [comment]
@MMarus LGTM, thanks!

**Comment by MMarus** [comment]
Hello @hpehl I have incorporated the changes into all classes which extend `FinderColumn` and moved the creation of the `UniqueNameValidation` into a method in the `FinderColumn` so it is easier to use it.

In the `PrincipalColumn` it is possible to create resource with the same name on a different realm so it validates whether resource with the name exists on the realm specified in the form.

I have also created a `NamedObject` interface and used it in the `NamedNode`, `Role`, `JdbcDriver` since they all have already `getName()` method. This adds ability to treat these classes the same and call the `getName()` regardless which of the three types is the actual one. This is used for example in the  [`FinderColumn`](https://github.com/hal/console/pull/241/files#diff-7a33e11253db4670bf2164a332a8d0fdR794).

Could you please review this PR?

**Comment by hpehl** [comment]
Thanks, @MMarus for the update. I'm preparing a HAL release for WildFly 14 atm. Once I'm done with the release I'll review the PR.

**Comment by MMarus** [comment]
Thank you @hpehl I'm looking forward to it :).

**Comment by hpehl** [comment]
Hi @MMarus. I'm back from PTO and will look into the PR soon.

**Comment by MMarus** [comment]
I just rebased this & fixed conflicts.

**Comment by hpehl** [comment]
Thanks, @MMarus. I've slightly adjusted some code on the PR. But all in all that was a really good contribution. Keep up the good work.

**Comment by MMarus** [comment]
Thank You very much!

**Pull request merged**
