### PR TITLE
HAL-1973 i18n korean translation

### PR DESCRIPTION
**Pull request by hanjeongsang**
Added Korean translation to HAL console.

- Translations familiar to Koreans, especially IT-related terms.
- Completed multiple reviews.

https://issues.redhat.com/browse/HAL-1973

### CODE REVIEW

**Comment by hanjeongsang** [comment]
I already knew there was a space character, so I modified it, but it was not reflected in the first commit.

**Comment by hanjeongsang** [comment]
the force push was made to modify Author in the commit log.

**Comment by hpehl** [comment]
Thanks @hanjeongsang 
This is huge 👏 👍

I need to check with the i18n team at Red Hat before merging that.

**Comment by hpehl** [comment]
Hi @hanjeongsang, 

Sorry for the long delay. Discussing your contribution with the HAL/WildFly team and related stakeholders took some time. 

First, let me thank you for your contribution! Unfortunately, we cannot yet merge user-contributed translations. We're currently evaluating a process that would make that possible, but we're not there yet. We envision something allowing us to ship HAL with predefined translations and add others.

Thanks again for your contribution. If you have further questions, please don't hesitate to contact me.

**Pull request closed without merging**
