### PR TITLE
[HAL-636] Enhancing the bootstrap server setup process

### PR DESCRIPTION
**Pull request by khermano**
https://issues.redhat.com/browse/HAL-636

### CODE REVIEW

**Comment by t-gergely** [comment]
Good. But I think the presented text strongly implies an incorrect configuration now, even if it can be a normal authorization failure (intended lack of privileges).

Handing error 503 while (re)loading the server would be welcome, too. :) A different situation with the same symptom.

**Comment by khermano** [comment]
I will look at that :)

**Comment by khermano** [comment]
I added 503 case. Is it good like that?

**Comment by t-gergely** [comment]
It's fine. Thanks.

**Pull request merged**
