### PR TITLE
HAL-1596: expose runtime attributes of jms-bridge

### PR DESCRIPTION
**Pull request by michpetrov**
Issue: [HAL-1596](https://issues.redhat.com/browse/HAL-1596)

### CODE REVIEW

**Comment by hpehl** [comment]
I'm currently preparing PR #510 to establish common rules for the codebase. #510 incorporates *many* changes. 

I'm not sure about the order of merging the PRs. I think there are two options:

1. Merge #510 first and then rebase the other PRs (including this PR).
2. Hold #510 until most / all other PRs have been merged (some PRs cannot be merged now, though)

Before going in any direction, I'd like to get feedback from you.

**Comment by michpetrov** [comment]
@hpehl all of my PRs should now be rebased, there were some manual tweaks required but otherwise it went smoothly

**Comment by hpehl** [comment]
Great! Thanks @michpetrov

**Comment by hpehl** [comment]
Thanks, @michpetrov for your contribution!

**Pull request merged**
