### PR TITLE
[HAL-1810] Adding String constants to the UIConstants and using in Co…

### PR DESCRIPTION
**Pull request by sarfarazgit**
…lumnActionFactory

### CODE REVIEW

**Comment by sarfarazgit** [comment]
Harald and Team!

Would you please review my pull request?

**Review by hpehl — CHANGES_REQUESTED** [review]
A quick search in the codebase showed that there are more occurrences of "add-circle-o" which could also be replaced by the constant. Please replace those occurrences as well.

**Comment by sarfarazgit** [comment]
@hpehl - All the suggested changes are updated and committed. Please review.

**Review by hpehl — APPROVED** [review]
LGTM! Thanks, @sarfarazgit

**Pull request merged**
