### PR TITLE
HAL-1658: fix address handling in composite operation

### PR DESCRIPTION
**Pull request by TomasHofman**
Issue: https://issues.redhat.com/browse/JBEAP-18911
Upstream issue: https://issues.redhat.com/browse/JBEAP-18910
Upstream PR: https://github.com/hal/console/pull/385

### CODE REVIEW

**Comment by TomasHofman** [comment]
@michpetrov would you review?

Compared to the original commit the `Composite` class constructor doesn't take the `address` argument, so I had to count with Composite address being `root` and I left out `.subTemplate(2,template.size())` on line 94.

**Comment by michpetrov** [comment]
@TomasHofman if the composite has no address then its child operations are all defaulting to master, aren't they? I'm expecting the composite to fail in case there are EJBs on slave that are not present on master. I would update the Composite.

**Comment by TomasHofman** [comment]
@michpetrov, I updated my PR to include also the change in the Composite class, I agree it's a better solution. But as I was retesting my backport I noticed that different errors started to pop up when I navigate to "EJB" subsystem on "source-server-group" > "source-node".

I checked current Wildfly and I can see the problem there too. I will reopen the upstream issue and can you please take a look?

**Comment by TomasHofman** [comment]
Thanks @michpetrov! I retested the reproducer and it looks fine.

**Pull request merged**
