### PR TITLE
[JBEAP-24529][HAL-1839] Properties in the Resource Adapter are removed when updating the connection pool with Management Console

### PR DESCRIPTION
**Pull request by lvydra**
https://issues.redhat.com/browse/HAL-1839
https://issues.redhat.com/browse/JBEAP-24529

### CODE REVIEW

**Comment by lvydra** [comment]
Hi @hpehl, sure, no problem, thanks.

**Comment by RanabirChakraborty** [comment]
Hello @hpehl If possible Can you please review this PR.

**Comment by hpehl** [comment]
Thanks, @RanabirChakraborty. I'll need some time until I can review the PR. I'm busy with other tasks.

**Review by hpehl — COMMENTED** [review]
Thanks for the contribution @lvydra 
Your solution works, but I found an issue with `GroupedForm<T>` and how the save callbacks are handled. So I opened another PR (https://github.com/hal/console/pull/820) to fix that.

**Comment by hpehl** [comment]
Superseded by https://github.com/hal/console/pull/820

**Pull request closed without merging**
