### PR TITLE
HAL-1637: fix datasource creation in standalone

### PR DESCRIPTION
**Pull request by michpetrov**
Issue: [HAL-1637](https://issues.jboss.org/browse/HAL-1637)

### CODE REVIEW

**Comment by rolaca11** [comment]
the issue persists to me even with this snapshot version installed

**Comment by michpetrov** [comment]
@rolaca11 can you tell me what buttons you're pressing? No instance of `runningServers` should be executed in standalone.

**Comment by rolaca11** [comment]
I was trying to view the list of drivers. I was navigating through `configuration -> datasources and drivers -> drivers` give or take (not able to access my server atm, so I can't check exactly). 

Same thing when adding datasources from the menu besides this.

**Comment by michpetrov** [comment]
@rolaca11 is it the `newValue is null` error? Are you sure this PR is included in the build you're running?

**Comment by rolaca11** [comment]
This is the `newValue is null` error and based on the fact that on the lower-right corner I see 3.2.2-SNAPSHOT version in HAL console, I'm quite sure I have the right version.

I'll double check when I get to it, but I remember checking out your fork and not the `hal:develop` branch. There is no reason for me to check out the `hal:develop` branch, but I did more stupid things in my life :D

**Comment by michpetrov** [comment]
well, it's a SNAPSHOT, you can't be sure what code is in and what isn't unless you check the logs

**Comment by hpehl** [comment]
Thanks for the fix @michpetrov. I found an alternative fix which doesn't require the `environment.isStandalone()` switch (see https://github.com/hal/console/commit/3816a13bc8e71071a54fe9a873896d37d4893bb9)

**Pull request closed without merging**
