### PR TITLE
HAL-1985: fix description processing for nested attributes

### PR DESCRIPTION
**Pull request by michpetrov**
Port of #1187

### CODE REVIEW

**Comment by soul2zimate** [comment]
please be careful to merge this into downstream branch. There are some issues raised due to HAL-1985

**Comment by hpehl** [comment]
@soul2zimate is it safe to merge this now?

**Comment by soul2zimate** [comment]
Hi @hpehl not yet, I backport my fix to your branch @michpetrov https://github.com/michpetrov/hal.next/pull/140, but I think QE mentioned a second issue caused by this change in https://issues.redhat.com/browse/HAL-1990

**Comment by michpetrov** [comment]
@hpehl @soul2zimate added a commit porting #1245

**Comment by soul2zimate** [comment]
I believe you also need HAL-1991 fix as well ?

**Pull request merged**
