### PR TITLE
[HAL-1952] Adding String constants in ExpressionEncryptor class.

### PR DESCRIPTION
**Pull request by SarafrazAhamad**
…rypt Expression code in the ExpressionEncryptor class

### CODE REVIEW

**Review by hpehl — CHANGES_REQUESTED** [review]
I would rather add the constants to `org.jboss.hal.dmr.ModelDescriptionConstants` and reference them.

**Comment by SarafrazAhamad** [comment]
@hpehl  - Thank you for your input. I will do the same and then submit the pull request.

**Review by hpehl — CHANGES_REQUESTED** [review]
Sorry for being picky, but the constants in `ModelDescriptionConstants` are sorted by name. Could you please reorder the new constants accordingly? Thanks!

**Comment by SarafrazAhamad** [comment]
@hpehl - The changes were completed as per the request and committed the changes.

**Pull request merged**
