### PR TITLE
HAL-1777: Replace ZeroClipboard with clipboardjs (3.3.x branch)

### PR DESCRIPTION
**Pull request by soul2zimate**
Issue: https://issues.redhat.com/browse/JBEAP-23740

HAL issue: https://issues.redhat.com/browse/HAL-1777

Upstream main branch PR: https://github.com/hal/console/pull/549

I also removed `ZeroClipboard` references in `Gruntfile.js`. But, Do I need to replace them with`clipboard` there?

### CODE REVIEW

**Comment by hpehl** [comment]
@soul2zimate Right, you have to include clipboardjs in the Gruntfile.

**Comment by soul2zimate** [comment]
> @soul2zimate Right, you have to include clipboardjs in the Gruntfile.

I have replaced with `clipboard.js` and `clipboard.min.js`, and just removed below ZeroClipboard.swf file copy:

```
                    {
                        expand: true,
                        cwd: '<%= config.node %>/zeroclipboard/dist',
                        src: 'ZeroClipboard.swf',
                        dest: '<%= config.public %>/js'
                    },
```

**Comment by hpehl** [comment]
LGTM. Have you tested that it works?

**Comment by soul2zimate** [comment]
Is there any particular test I need to run ? 

I have built EAP with this replacement included. The `ZeroClipboard.swf` file is gone. I can successfully open the web console.

**Comment by hpehl** [comment]
Unfortunately, there's no automatic test for this. Could you please open a log file in the runtime section and try to copy the content of the log file to the clipboard. If that works, the PR works!

**Comment by soul2zimate** [comment]
yep, I have clicked the `Copy to clipboard` button and  a `"Copied!"` message flickers. As a result, the log content is copied.

**Comment by hpehl** [comment]
Great! Then everything should be fine. This PR can then go into the next CP release for EAP 7.4.x

**Pull request merged**
