### PR TITLE
Upgrade to rxjava 2

### PR DESCRIPTION
**Pull request by ibaca**

### CODE REVIEW

**Comment by hpehl** [comment]
Does GWT 2.8.2 work with RxJava 2 out of the box? Is a custom GWT build still necessary?

**Comment by ibaca** [comment]
Nop 😞, it needs the custom build. I get it work too late and they consider it was not a good idea. I really hope it gets included in 2.8.3, one good thing is that it will get forced to update JDT for java9, so it needs to be fixed at that moment.

**Comment by hpehl** [comment]
@ibaca Is there an update about RxJava2 support for GWT 2.8.x? If not I think I'm going to close this PR.

**Comment by ibaca** [comment]
Oh, it is already RxJava 3 available and we haven't still migrated to RxJava 2 😞, the problem is still the same, the last GWT release doesn't work with RxJava 2 generics correctly. Anyway, you really should create your own GWT release form HEAD, we have been using java 11 for more than a year, and I suppose you are still locked in java8. If you do something similar to my rx1, something like gwt-2.9.0-hal1, you can finally migrate to RxJava 2, start using "var", or just keep your code up to date so when GWT finally make a release, 2.9 or 3.0, you will be already compatible.

**Comment by ibaca** [comment]
Anyway, I'm going to close this. I can repeat the process, maybe even with fewer changes. So it makes no sense to keep it open.

**Comment by hpehl** [comment]
Thanks for the update @ibaca

**Pull request closed without merging**
