### PR TITLE
[JBEAP-21565] [HAL-1742] [HAL-1749] Fix address parsing when address contains duplicate parts

### PR DESCRIPTION
**Pull request by rmartinc**
Upstream Issue: https://issues.redhat.com/browse/HAL-1742
Upstream PR: https://github.com/hal/console/pull/462
Issue: https://issues.redhat.com/browse/JBEAP-21565

Adding the commit in the related upstream PR and the one that removed the unneeded imports in the class (it was merged later).

### CODE REVIEW

**Comment by hpehl** [comment]
Thanks @rmartinc !

**Comment by hpehl** [comment]
@rmartinc Unfortunately [HAL-1742](https://issues.redhat.com/browse/HAL-1742) introduced a bug fixed by [HAL-1749](https://issues.redhat.com/browse/HAL-1749). Could you please add the commits to HAL-1749 to this PR? Thanks!

**Comment by rmartinc** [comment]
@hpehl I don't see that commit in the develop branch which is weird. The commit says that does not belong to any branch on this repository and the contents inside [ResourceAddress.java](https://github.com/hal/console/commits/develop/dmr/src/main/java/org/jboss/hal/dmr/ResourceAddress.java) seem to be the same. It's like the commit in that PR doesn't exist in the develop branch although I see it merged. Can you check please?

**Comment by hpehl** [comment]
@rmartinc You're right. Looks like something went wrong when I commit / merged the PR. I'm going to file a new JBEAP issue and open another PR to backport HAL-1749 to 3.2.x

**Comment by rmartinc** [comment]
Thanks @hpehl! I'll include the commit ASAP in this backport when it's ready.

**Comment by hpehl** [comment]
@rmartinc I have re-submitted the fix for HAL-1749. Now we've got a valid commit on branch develop, we can use for the backport (don't have a clue what went wrong with the first commit 🤷‍♂️)

Could you please include https://github.com/hal/console/pull/467/commits/4b35d8f0adf565769a63bfa9d062c614ea08dd8f int this backport? Thanks!

**Comment by rmartinc** [comment]
Done!

**Comment by hpehl** [comment]
Thanks @rmartinc !

**Pull request merged**
