### PR TITLE
HAL-1847: fix JDBC driver forms following driver-name deprecation

### PR DESCRIPTION
**Pull request by michpetrov**
Issue: [HAL-1847](https://issues.redhat.com/browse/HAL-1847)

The attribute will become deprecated in the next release, the PR is already merged.

### CODE REVIEW

**Review by hpehl — APPROVED** [review]
Thanks, @michpetrov, for the fix! Very much appreciated!

**Comment by idafalco** [comment]
In administration console of wildfly28, in Add Datasource i can't add the driver. While in older version of wildfy there was a dropdown menu 'driver name' in which we can select the Driver. The driver association fails and the test connection fails. How should I do?

**Comment by hpehl** [comment]
@idafalco, could you please give more context? What exactly are you trying to do? And what older version are you referring to?

**Comment by idafalco** [comment]
@hpehl 
From the Administration web console of Wildfly 28, I deployed the java-mysql connector jar file (8.0.31) with the 'Upload Deployment' tab.
After that, in Configuration -> Subsystem -> Datasources & Drivers -> Datasources -> Add Datasource. In the form I select MySQL datasources, I set my attribute (JNDI Name). In the next 'JDBC Driver' form I have this:

image_2023_05_19T15_24_28_638Z
In this form I can't associate the deployed driver.

Instead, in a previous version of Wildfly, this form have a dropdown menu in wich select the driver:

image_2023_05_20T13_02_39_854Z

**Comment by idafalco** [comment]
@hpehl Thanks

**Comment by hpehl** [comment]
@idafalco I can confirm that this is broken in HAL 3.6.5.Final. This PR and #837 fix it, and it will work again in the next release.

**Pull request merged**
