### PR TITLE
HAL-1742: Fix address parsing when address contains duplicate parts

### PR DESCRIPTION
**Pull request by hpehl**
https://issues.redhat.com/browse/HAL-1742

### CODE REVIEW

**Comment by rmartinc** [comment]
@hpehl I was working in the same issue (JBEAP jira) and I think that two imports (Map and Splitter) that are not needed were missing in the class. The compilation fails now with:

```
[ERROR] src/main/java/org/jboss/hal/dmr/ResourceAddress.java:[21,8] (imports) UnusedImports: Unused import - java.util.Map.
[ERROR] src/main/java/org/jboss/hal/dmr/ResourceAddress.java:[23,8] (imports) UnusedImports: Unused import - com.google.common.base.Splitter.
```

It's just that, the fix is OK if I remove those unneeded imports...

**Comment by hpehl** [comment]
@rmartinc Yeah, unfortunately I forgot to organize imports after I pushed the fix 😐

**Comment by soul2zimate** [comment]
@hpehl I see a new internal error seems related to this fix:

`Unable to load required resources for column 'standalone-server-column': Error: java.lang.IllegalArgumentException: Malformed part '' in address: /`

Steps to reproduce:

1. Start the server in standalone.
2. Go to Runtime (first time is good), refresh the page.
3. Above internal error appears and the Runtime page is unavailable anymore.

It looks like the fix does not omit empty string in case of root / address.

**Comment by hpehl** [comment]
Thanks @soul2zimate for bringing this up. That's indeed a regression introduced by this fix.

**Pull request merged**
